functionsDirectory = "/Users/vsudagani/Desktop/#business/T2M/T2MSite/site/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/vsudagani/Desktop/#business/T2M/T2MSite/site"
publishOrigin = "default"
functions = "/Users/vsudagani/Desktop/#business/T2M/T2MSite/site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
functions = "netlify/functions"
targetPort = 8888.0

[functions]

[functions."*"]

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/app"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/transcribe"
to = "/.netlify/functions/transcribe"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/spotify-search"
to = "/.netlify/functions/spotify-search"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/vision"
to = "/.netlify/functions/vision"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/summarize"
to = "/.netlify/functions/summarize"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]