-- Proactive Blak: the engine behind a friend that reaches out.
--
-- blak_nudges  — Blak-initiated nudges (follow-throughs scheduled per-turn, plus
--                time-based check-ins/rhythm/silence/wins generated by the cron).
-- blak_prefs   — per-user proactivity level (none | low | default | high) that
--                gates how many nudges Blak may generate per day.
--
-- Owner-only RLS so the browser reads/acts on its own nudges directly; the cron
-- and per-turn learner write with the service role, always scoped to user_id.

create table if not exists public.blak_nudges (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null,
    kind       text not null,                         -- followthrough | checkin | morning | evening | silence | win
    text       text not null,                         -- what Blak will say
    context    text,                                  -- internal: why (not shown verbatim)
    due_at     timestamptz not null default now(),
    status     text not null default 'pending',       -- pending | shown | acted | dismissed
    created_at timestamptz not null default now()
);
alter table public.blak_nudges enable row level security;
drop policy if exists "own nudges" on public.blak_nudges;
create policy "own nudges" on public.blak_nudges
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create index if not exists blak_nudges_due_idx on public.blak_nudges (user_id, status, due_at);

create table if not exists public.blak_prefs (
    user_id      uuid primary key,
    proactivity  text not null default 'default',     -- none | low | default | high
    last_nudge_at timestamptz,
    updated_at   timestamptz not null default now()
);
alter table public.blak_prefs enable row level security;
drop policy if exists "own prefs" on public.blak_prefs;
create policy "own prefs" on public.blak_prefs
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
